Add rspec tests for the caesar_cipher method
yaeluria/ruby-assignments pull request #6
Opened 2022-06-26 08:22 UTC by yaeluria

Assignment 1. Task 1.
https://www.theodinproject.com/lessons/ruby-connect-four

2022-06-26 13:44 UTC, tuval10 requested changes

2022-06-26 13:44 UTC, tuval10 commented on spec/caesar_cipher_spec.rb
> +end
Problem 1:
you need to start using context - see https://www.betterspecs.org/#contexts (better read everything in this site - they give good tips)
for example context here that you should have
```
context 'when shift_num is bigger than the letters count' do

end

context 'when shift_num is negative' do
end

context 'when string contains not alphabetic characters' do
end

context 'when string contain uppercase letters' do
end

context 'when string is empty' do
end
```
***

Problem 2
use `let` in your test - https://dev.to/isalevine/intro-to-rspec-in-rails-part-2-improving-tests-with-let-and-context-241n

Then it will look like:
(I'm giving you example for one context - and you can write the others)
```
describe '#caesar_cipher' do
  let(:string) { 'incredible' }
  let(:expected_result) { 'kpetgfkdng' }
  let(:shift_num) { 2 }
  let(:method_result) { caesar_cipher(string, shift_num) }

  it { expect(method_result).to eq expected_result }

  context 'when shift_num is bigger than the alphabet size' do
    let(:letters_count) { 26 }
    let(:shift_num) { 2 + letters_count * 3 }

    it { expect(method_result).to eq expected_result }
  end
end
```

2022-06-27 14:03 UTC, yaeluria commented on spec/caesar_cipher_spec.rb
> +end
done

2022-06-27 15:07 UTC, tuval10 approved these changes

2022-06-27 15:07 UTC, merged